[2025-08-09 12:25:18,178: INFO: main: Logging has been set up successfully.]
[2025-08-16 13:03:09,321: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 13:03:09,323: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 13:03:09,324: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 13:03:09,325: INFO: common: created directory at: artifacts]
[2025-08-16 13:03:09,325: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 13:03:27,348: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 13:03:27,349: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 13:03:27,350: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 13:03:27,350: INFO: common: created directory at: artifacts]
[2025-08-16 13:03:27,351: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 13:04:30,373: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 13:04:30,374: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 13:04:30,375: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 13:04:30,375: INFO: common: created directory at: artifacts]
[2025-08-16 13:04:30,376: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 13:04:30,786: INFO: 251335794: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: EECE:33D4EC:188B5:15BCB7:68A073C9
Accept-Ranges: bytes
Date: Sat, 16 Aug 2025 12:04:30 GMT
Via: 1.1 varnish
X-Served-By: cache-dub4324-DUB
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1755345871.739376,VS0,VE105
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 4cf97b60f81aa6fca8ae6702897aae0f7295e1ec
Expires: Sat, 16 Aug 2025 12:09:30 GMT
Source-Age: 0

]
[2025-08-16 13:21:12,513: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 13:21:12,514: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 13:21:12,514: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 13:21:12,514: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 13:21:12,514: INFO: common: created directory at: artifacts]
[2025-08-16 13:21:12,514: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 13:21:12,897: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: EECE:33D4EC:188B5:15BCB7:68A073C9
Accept-Ranges: bytes
Date: Sat, 16 Aug 2025 12:21:12 GMT
Via: 1.1 varnish
X-Served-By: cache-dub4336-DUB
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1755346873.843298,VS0,VE106
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 8d0ae453f2953d6143c7d2fd31bc833c5bb49042
Expires: Sat, 16 Aug 2025 12:26:12 GMT
Source-Age: 0

]
[2025-08-16 13:21:12,901: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 13:43:38,961: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 13:43:38,962: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 13:43:38,964: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 13:43:38,964: INFO: common: created directory at: artifacts]
[2025-08-16 13:43:38,965: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 13:43:55,569: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 13:43:55,570: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 13:43:55,572: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 13:43:55,573: INFO: common: created directory at: artifacts]
[2025-08-16 13:43:55,573: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 13:43:55,573: ERROR: 297557633: "'ConfigBox' object has no attribute 'all_schema'"]
Traceback (most recent call last):
  File "box/box.py", line 594, in box.box.Box.__getitem__
KeyError: 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 633, in box.box.Box.__getattr__
  File "box/box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'all_schema'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'all_schema'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 594, in box.box.Box.__getitem__
KeyError: 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 633, in box.box.Box.__getattr__
  File "box/box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'all_schema'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/folders/zk/l_pq96ms1qvfyjkxyzyz0qgm0000gn/T/ipykernel_5056/297557633.py", line 3, in <module>
    data_validation_config = config.get_data_validation_config()
  File "/var/folders/zk/l_pq96ms1qvfyjkxyzyz0qgm0000gn/T/ipykernel_5056/1712767539.py", line 25, in get_data_validation_config
    all_schema=config.all_schema
  File "box/config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'all_schema'"
[2025-08-16 13:47:52,916: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 13:47:52,917: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 13:47:52,919: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 13:47:52,919: INFO: common: created directory at: artifacts]
[2025-08-16 13:47:52,920: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 13:47:52,920: ERROR: 2519673437: "'ConfigBox' object has no attribute 'all_schema'"]
Traceback (most recent call last):
  File "box/box.py", line 594, in box.box.Box.__getitem__
KeyError: 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 633, in box.box.Box.__getattr__
  File "box/box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'all_schema'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'all_schema'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 594, in box.box.Box.__getitem__
KeyError: 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 633, in box.box.Box.__getattr__
  File "box/box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'all_schema'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/folders/zk/l_pq96ms1qvfyjkxyzyz0qgm0000gn/T/ipykernel_5056/2519673437.py", line 3, in <module>
    data_validation_config = config.get_data_validation_config()
  File "/var/folders/zk/l_pq96ms1qvfyjkxyzyz0qgm0000gn/T/ipykernel_5056/1712767539.py", line 25, in get_data_validation_config
    all_schema=config.all_schema
  File "box/config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'all_schema'"
[2025-08-16 13:50:03,919: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 13:50:03,920: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 13:50:03,923: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 13:50:03,924: INFO: common: created directory at: artifacts]
[2025-08-16 13:50:03,924: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 13:50:03,925: ERROR: 2519673437: "'ConfigBox' object has no attribute 'all_schema'"]
Traceback (most recent call last):
  File "box/box.py", line 594, in box.box.Box.__getitem__
KeyError: 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 633, in box.box.Box.__getattr__
  File "box/box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'all_schema'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'all_schema'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 594, in box.box.Box.__getitem__
KeyError: 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 633, in box.box.Box.__getattr__
  File "box/box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'all_schema'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'all_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/folders/zk/l_pq96ms1qvfyjkxyzyz0qgm0000gn/T/ipykernel_5056/2519673437.py", line 3, in <module>
    data_validation_config = config.get_data_validation_config()
  File "/var/folders/zk/l_pq96ms1qvfyjkxyzyz0qgm0000gn/T/ipykernel_5056/1712767539.py", line 25, in get_data_validation_config
    all_schema=config.all_schema
  File "box/config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'all_schema'"
[2025-08-16 13:51:24,344: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 13:51:24,346: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 13:51:24,347: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 13:51:24,348: INFO: common: created directory at: artifacts]
[2025-08-16 13:51:24,348: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 14:10:36,340: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 14:10:36,342: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 14:10:36,342: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 14:10:36,342: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 14:10:36,342: INFO: common: created directory at: artifacts]
[2025-08-16 14:10:36,343: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 14:10:36,343: INFO: data_ingestion: File already exists]
[2025-08-16 14:10:36,344: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 14:10:36,344: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 14:10:36,344: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 14:10:36,345: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 14:10:36,345: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 14:10:36,345: INFO: common: created directory at: artifacts]
[2025-08-16 14:10:36,345: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 14:10:36,348: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 14:32:34,075: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 14:32:34,076: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 14:32:34,078: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 14:32:34,079: INFO: common: created directory at: artifacts]
[2025-08-16 14:32:34,080: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 14:32:34,096: INFO: 741865018: Splited data into training and test sets]
[2025-08-16 14:32:34,096: INFO: 741865018: (1199, 12)]
[2025-08-16 14:32:34,096: INFO: 741865018: (400, 12)]
[2025-08-16 14:48:22,297: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 14:48:22,298: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 14:48:22,298: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 14:48:22,298: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 14:48:22,299: INFO: common: created directory at: artifacts]
[2025-08-16 14:48:22,299: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 14:48:22,299: INFO: data_ingestion: File already exists]
[2025-08-16 14:48:22,300: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 14:48:22,300: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 14:48:22,301: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 14:48:22,301: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 14:48:22,301: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 14:48:22,301: INFO: common: created directory at: artifacts]
[2025-08-16 14:48:22,301: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 14:48:22,304: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 14:48:22,304: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 14:48:22,305: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 14:48:22,305: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 14:48:22,306: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 14:48:22,306: INFO: common: created directory at: artifacts]
[2025-08-16 14:48:22,306: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 14:48:22,313: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 14:48:22,313: INFO: data_transformation: (1199, 12)]
[2025-08-16 14:48:22,313: INFO: data_transformation: (400, 12)]
[2025-08-16 14:48:22,313: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 14:48:42,756: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 14:48:42,758: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 14:48:42,758: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 14:48:42,758: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 14:48:42,759: INFO: common: created directory at: artifacts]
[2025-08-16 14:48:42,759: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 14:48:42,759: INFO: data_ingestion: File already exists]
[2025-08-16 14:48:42,760: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 14:48:42,760: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 14:48:42,760: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 14:48:42,760: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 14:48:42,761: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 14:48:42,761: INFO: common: created directory at: artifacts]
[2025-08-16 14:48:42,761: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 14:48:42,763: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 14:48:42,763: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 14:48:42,764: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 14:48:42,764: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 14:48:42,765: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 14:48:42,765: INFO: common: created directory at: artifacts]
[2025-08-16 14:48:42,765: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 14:48:42,771: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 14:48:42,771: INFO: data_transformation: (1199, 12)]
[2025-08-16 14:48:42,772: INFO: data_transformation: (400, 12)]
[2025-08-16 14:48:42,772: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 15:34:39,655: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 15:34:39,656: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 15:34:39,659: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 15:34:39,659: INFO: common: created directory at: artifacts]
[2025-08-16 15:34:39,660: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 15:44:50,737: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 15:44:50,739: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 15:44:50,739: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 15:44:50,740: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 15:44:50,740: INFO: common: created directory at: artifacts]
[2025-08-16 15:44:50,740: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 15:44:50,740: INFO: data_ingestion: File already exists]
[2025-08-16 15:44:50,741: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 15:44:50,741: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 15:44:50,742: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 15:44:50,742: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 15:44:50,743: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 15:44:50,743: INFO: common: created directory at: artifacts]
[2025-08-16 15:44:50,743: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 15:44:50,745: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 15:44:50,745: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 15:44:50,746: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 15:44:50,746: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 15:44:50,747: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 15:44:50,747: INFO: common: created directory at: artifacts]
[2025-08-16 15:44:50,747: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 15:44:50,754: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 15:44:50,754: INFO: data_transformation: (1199, 12)]
[2025-08-16 15:44:50,754: INFO: data_transformation: (400, 12)]
[2025-08-16 15:44:50,754: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 15:44:50,754: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 15:44:50,755: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 15:44:50,755: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 15:44:50,756: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 15:44:50,756: INFO: common: created directory at: artifacts]
[2025-08-16 15:44:50,756: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 15:44:50,759: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 15:45:11,537: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 15:45:11,538: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 15:45:11,539: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 15:45:11,539: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 15:45:11,539: INFO: common: created directory at: artifacts]
[2025-08-16 15:45:11,539: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 15:45:11,539: INFO: data_ingestion: File already exists]
[2025-08-16 15:45:11,540: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 15:45:11,540: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 15:45:11,541: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 15:45:11,541: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 15:45:11,542: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 15:45:11,542: INFO: common: created directory at: artifacts]
[2025-08-16 15:45:11,542: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 15:45:11,544: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 15:45:11,544: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 15:45:11,545: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 15:45:11,545: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 15:45:11,546: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 15:45:11,546: INFO: common: created directory at: artifacts]
[2025-08-16 15:45:11,546: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 15:45:11,553: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 15:45:11,553: INFO: data_transformation: (1199, 12)]
[2025-08-16 15:45:11,553: INFO: data_transformation: (400, 12)]
[2025-08-16 15:45:11,553: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 15:45:11,553: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 15:45:11,554: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 15:45:11,554: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 15:45:11,555: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 15:45:11,555: INFO: common: created directory at: artifacts]
[2025-08-16 15:45:11,555: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 15:45:11,558: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 16:10:41,377: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:10:41,378: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:10:41,380: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:10:41,381: INFO: common: created directory at: artifacts]
[2025-08-16 16:10:41,382: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:10:42,671: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:15:11,608: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:15:11,610: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:15:11,611: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:15:11,612: INFO: common: created directory at: artifacts]
[2025-08-16 16:15:11,613: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:15:12,089: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:22:16,385: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:22:16,386: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:22:16,388: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:22:16,389: INFO: common: created directory at: artifacts]
[2025-08-16 16:22:16,389: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:22:47,128: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:22:47,129: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:22:47,131: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:22:47,131: INFO: common: created directory at: artifacts]
[2025-08-16 16:22:47,132: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:22:47,414: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:23:25,011: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:23:25,012: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:23:25,014: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:23:25,014: INFO: common: created directory at: artifacts]
[2025-08-16 16:23:25,015: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:23:25,310: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:37:30,011: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 16:37:30,013: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:37:30,013: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:37:30,014: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:37:30,014: INFO: common: created directory at: artifacts]
[2025-08-16 16:37:30,014: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 16:37:30,014: INFO: data_ingestion: File already exists]
[2025-08-16 16:37:30,015: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 16:37:30,015: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 16:37:30,016: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:37:30,017: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:37:30,017: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:37:30,017: INFO: common: created directory at: artifacts]
[2025-08-16 16:37:30,017: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 16:37:30,020: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 16:37:30,020: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 16:37:30,021: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:37:30,021: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:37:30,022: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:37:30,022: INFO: common: created directory at: artifacts]
[2025-08-16 16:37:30,022: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 16:37:30,029: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 16:37:30,029: INFO: data_transformation: (1199, 12)]
[2025-08-16 16:37:30,029: INFO: data_transformation: (400, 12)]
[2025-08-16 16:37:30,029: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 16:37:30,029: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 16:37:30,030: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:37:30,031: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:37:30,031: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:37:30,031: INFO: common: created directory at: artifacts]
[2025-08-16 16:37:30,031: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 16:37:30,035: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 16:37:30,035: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 16:37:30,036: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:37:30,036: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:37:30,037: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:37:30,037: INFO: common: created directory at: artifacts]
[2025-08-16 16:37:30,037: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:37:30,273: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:37:30,279: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 16:43:11,326: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 16:43:11,327: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:43:11,327: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:43:11,328: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:43:11,328: INFO: common: created directory at: artifacts]
[2025-08-16 16:43:11,328: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 16:43:11,328: INFO: data_ingestion: File already exists]
[2025-08-16 16:43:11,329: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 16:43:11,329: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 16:43:11,330: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:43:11,331: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:43:11,331: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:43:11,331: INFO: common: created directory at: artifacts]
[2025-08-16 16:43:11,331: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 16:43:11,334: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 16:43:11,334: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 16:43:11,335: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:43:11,335: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:43:11,336: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:43:11,336: INFO: common: created directory at: artifacts]
[2025-08-16 16:43:11,336: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 16:43:11,343: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 16:43:11,343: INFO: data_transformation: (1199, 12)]
[2025-08-16 16:43:11,343: INFO: data_transformation: (400, 12)]
[2025-08-16 16:43:11,343: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 16:43:11,343: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 16:43:11,344: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:43:11,345: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:43:11,345: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:43:11,345: INFO: common: created directory at: artifacts]
[2025-08-16 16:43:11,345: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 16:43:11,349: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 16:43:11,349: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 16:43:11,350: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:43:11,350: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:43:11,351: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:43:11,351: INFO: common: created directory at: artifacts]
[2025-08-16 16:43:11,351: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:43:11,578: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:43:13,094: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 16:46:22,005: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 16:46:22,006: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:46:22,006: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:46:22,007: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:46:22,007: INFO: common: created directory at: artifacts]
[2025-08-16 16:46:22,007: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 16:46:22,007: INFO: data_ingestion: File already exists]
[2025-08-16 16:46:22,008: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 16:46:22,008: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 16:46:22,009: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:46:22,010: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:46:22,010: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:46:22,010: INFO: common: created directory at: artifacts]
[2025-08-16 16:46:22,010: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 16:46:22,013: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 16:46:22,013: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 16:46:22,014: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:46:22,014: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:46:22,015: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:46:22,015: INFO: common: created directory at: artifacts]
[2025-08-16 16:46:22,015: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 16:46:22,022: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 16:46:22,022: INFO: data_transformation: (1199, 12)]
[2025-08-16 16:46:22,022: INFO: data_transformation: (400, 12)]
[2025-08-16 16:46:22,022: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 16:46:22,022: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 16:46:22,023: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:46:22,023: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:46:22,024: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:46:22,024: INFO: common: created directory at: artifacts]
[2025-08-16 16:46:22,024: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 16:46:22,027: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 16:46:22,027: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 16:46:22,028: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:46:22,029: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:46:22,029: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:46:22,029: INFO: common: created directory at: artifacts]
[2025-08-16 16:46:22,029: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:46:22,260: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:46:23,679: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 16:47:10,534: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 16:47:10,536: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:47:10,536: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:47:10,537: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:47:10,537: INFO: common: created directory at: artifacts]
[2025-08-16 16:47:10,537: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 16:47:10,537: INFO: data_ingestion: File already exists]
[2025-08-16 16:47:10,538: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 16:47:10,538: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 16:47:10,539: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:47:10,540: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:47:10,540: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:47:10,540: INFO: common: created directory at: artifacts]
[2025-08-16 16:47:10,540: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 16:47:10,543: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 16:47:10,543: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 16:47:10,544: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:47:10,544: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:47:10,545: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:47:10,545: INFO: common: created directory at: artifacts]
[2025-08-16 16:47:10,545: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 16:47:10,552: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 16:47:10,552: INFO: data_transformation: (1199, 12)]
[2025-08-16 16:47:10,552: INFO: data_transformation: (400, 12)]
[2025-08-16 16:47:10,552: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 16:47:10,552: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 16:47:10,553: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:47:10,553: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:47:10,554: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:47:10,554: INFO: common: created directory at: artifacts]
[2025-08-16 16:47:10,554: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 16:47:10,557: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 16:47:10,557: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 16:47:10,558: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:47:10,559: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:47:10,559: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:47:10,559: INFO: common: created directory at: artifacts]
[2025-08-16 16:47:10,559: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:47:10,785: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:47:10,791: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 16:47:40,157: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 16:47:40,158: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:47:40,158: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:47:40,159: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:47:40,159: INFO: common: created directory at: artifacts]
[2025-08-16 16:47:40,159: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 16:47:40,159: INFO: data_ingestion: File already exists]
[2025-08-16 16:47:40,160: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 16:47:40,160: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 16:47:40,161: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:47:40,162: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:47:40,162: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:47:40,162: INFO: common: created directory at: artifacts]
[2025-08-16 16:47:40,162: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 16:47:40,165: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 16:47:40,165: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 16:47:40,166: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:47:40,166: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:47:40,167: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:47:40,167: INFO: common: created directory at: artifacts]
[2025-08-16 16:47:40,167: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 16:47:40,174: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 16:47:40,174: INFO: data_transformation: (1199, 12)]
[2025-08-16 16:47:40,174: INFO: data_transformation: (400, 12)]
[2025-08-16 16:47:40,174: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 16:47:40,174: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 16:47:40,175: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:47:40,175: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:47:40,176: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:47:40,176: INFO: common: created directory at: artifacts]
[2025-08-16 16:47:40,176: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 16:47:40,179: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 16:47:40,179: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 16:47:40,180: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:47:40,181: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:47:40,181: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:47:40,181: INFO: common: created directory at: artifacts]
[2025-08-16 16:47:40,181: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:47:40,414: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:47:40,419: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 16:49:21,086: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 16:49:21,087: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:49:21,088: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:49:21,088: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:49:21,089: INFO: common: created directory at: artifacts]
[2025-08-16 16:49:21,089: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 16:49:21,089: INFO: data_ingestion: File already exists]
[2025-08-16 16:49:21,090: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 16:49:21,090: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 16:49:21,091: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:49:21,091: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:49:21,092: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:49:21,092: INFO: common: created directory at: artifacts]
[2025-08-16 16:49:21,092: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 16:49:21,094: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 16:49:21,094: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 16:49:21,095: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:49:21,095: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:49:21,096: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:49:21,096: INFO: common: created directory at: artifacts]
[2025-08-16 16:49:21,096: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 16:49:21,103: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 16:49:21,104: INFO: data_transformation: (1199, 12)]
[2025-08-16 16:49:21,104: INFO: data_transformation: (400, 12)]
[2025-08-16 16:49:21,104: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 16:49:21,104: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 16:49:21,105: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:49:21,105: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:49:21,105: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:49:21,106: INFO: common: created directory at: artifacts]
[2025-08-16 16:49:21,106: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 16:49:21,109: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 16:49:21,109: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 16:49:21,110: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:49:21,110: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:49:21,111: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:49:21,111: INFO: common: created directory at: artifacts]
[2025-08-16 16:49:21,111: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:49:21,679: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:49:24,025: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 16:51:53,003: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 16:51:53,004: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:51:53,005: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:51:53,005: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:51:53,005: INFO: common: created directory at: artifacts]
[2025-08-16 16:51:53,005: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 16:51:53,006: INFO: data_ingestion: File already exists]
[2025-08-16 16:51:53,007: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 16:51:53,007: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 16:51:53,008: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:51:53,008: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:51:53,008: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:51:53,008: INFO: common: created directory at: artifacts]
[2025-08-16 16:51:53,008: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 16:51:53,011: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 16:51:53,011: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 16:51:53,012: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:51:53,012: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:51:53,013: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:51:53,013: INFO: common: created directory at: artifacts]
[2025-08-16 16:51:53,013: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 16:51:53,020: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 16:51:53,020: INFO: data_transformation: (1199, 12)]
[2025-08-16 16:51:53,020: INFO: data_transformation: (400, 12)]
[2025-08-16 16:51:53,020: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 16:51:53,020: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 16:51:53,021: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:51:53,022: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:51:53,022: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:51:53,022: INFO: common: created directory at: artifacts]
[2025-08-16 16:51:53,022: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 16:51:53,026: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 16:51:53,026: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 16:51:53,027: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:51:53,027: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:51:53,028: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:51:53,028: INFO: common: created directory at: artifacts]
[2025-08-16 16:51:53,028: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:51:53,607: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:51:57,494: ERROR: main: INTERNAL_ERROR: Response: {'error': 'unsupported endpoint, please contact support@dagshub.com'}]
Traceback (most recent call last):
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/main.py", line 55, in <module>
    model_evaluation.initiate_model_evaluation()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/src/MLOPS/pipeline/model_evaul_pipeline.py", line 18, in initiate_model_evaluation
    model_evaluation.log_into_mlflow()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/src/MLOPS/components/model_evaual.py", line 67, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model", registered_model_name="ElasticnetModel")
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/mlflow/sklearn/__init__.py", line 426, in log_model
    return Model.log(
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/mlflow/models/model.py", line 1166, in log
    model = _create_logged_model(
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 2282, in _create_logged_model
    return MlflowClient()._create_logged_model(
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/mlflow/tracking/client.py", line 5379, in _create_logged_model
    return self._tracking_client.create_logged_model(
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/mlflow/telemetry/track.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 841, in create_logged_model
    return self.store.create_logged_model(
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 823, in create_logged_model
    response_proto = self._call_endpoint(CreateLoggedModel, req_body)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 133, in _call_endpoint
    return call_endpoint(
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 553, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 308, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INTERNAL_ERROR: Response: {'error': 'unsupported endpoint, please contact support@dagshub.com'}
[2025-08-16 16:52:29,096: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 16:52:29,097: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:52:29,097: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:52:29,098: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:52:29,098: INFO: common: created directory at: artifacts]
[2025-08-16 16:52:29,098: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 16:52:29,098: INFO: data_ingestion: File already exists]
[2025-08-16 16:52:29,099: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 16:52:29,099: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 16:52:29,100: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:52:29,100: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:52:29,101: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:52:29,101: INFO: common: created directory at: artifacts]
[2025-08-16 16:52:29,101: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 16:52:29,103: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 16:52:29,103: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 16:52:29,104: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:52:29,105: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:52:29,105: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:52:29,105: INFO: common: created directory at: artifacts]
[2025-08-16 16:52:29,105: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 16:52:29,112: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 16:52:29,112: INFO: data_transformation: (1199, 12)]
[2025-08-16 16:52:29,112: INFO: data_transformation: (400, 12)]
[2025-08-16 16:52:29,112: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 16:52:29,112: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 16:52:29,113: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:52:29,114: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:52:29,114: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:52:29,114: INFO: common: created directory at: artifacts]
[2025-08-16 16:52:29,114: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 16:52:29,119: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 16:52:29,119: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 16:52:29,120: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 16:52:29,120: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 16:52:29,120: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 16:52:29,121: INFO: common: created directory at: artifacts]
[2025-08-16 16:52:29,121: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 16:52:29,679: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 16:52:31,935: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 17:18:15,722: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.36:8080]
[2025-08-16 17:18:15,722: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-16 17:18:23,046: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/app.py", line 12, in home
    return render_template('index.html')
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/templates/index.html", line 197, in top-level template code
    <form class="needs-validation" action="{{ url_for('predict') }}" method="post" novalidate>
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict'. Did you mean 'static' instead?
[2025-08-16 17:18:23,048: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:18:23] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2025-08-16 17:18:23,060: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:18:23] "[33mGET /apple-touch-icon-precomposed.png HTTP/1.1[0m" 404 -]
[2025-08-16 17:18:23,071: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:18:23] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-08-16 17:18:23,136: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:18:23] "[33mGET /apple-touch-icon.png HTTP/1.1[0m" 404 -]
[2025-08-16 17:18:25,370: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/app.py", line 12, in home
    return render_template('index.html')
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/templates/index.html", line 197, in top-level template code
    <form class="needs-validation" action="{{ url_for('predict') }}" method="post" novalidate>
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict'. Did you mean 'static' instead?
[2025-08-16 17:18:25,372: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:18:25] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2025-08-16 17:19:40,930: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.36:8080]
[2025-08-16 17:19:40,930: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-16 17:19:58,257: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/app.py", line 12, in home
    return render_template('index.html')
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/templates/index.html", line 197, in top-level template code
    <form class="needs-validation" action="{{ url_for('predict') }}" method="post" novalidate>
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict'. Did you mean 'static' instead?
[2025-08-16 17:19:58,260: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:19:58] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2025-08-16 17:21:06,487: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.36:8080]
[2025-08-16 17:21:06,487: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-16 17:21:08,984: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:21:08] "GET / HTTP/1.1" 200 -]
[2025-08-16 17:21:08,990: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:21:08] "[33mGET /static/assets/img/form-v9.jpg HTTP/1.1[0m" 404 -]
[2025-08-16 17:23:03,000: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.36:8080]
[2025-08-16 17:23:03,000: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-16 17:23:05,533: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/app.py", line 12, in home
    return render_template('index.html')
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/templates/index.html", line 18, in top-level template code
    <form action="{{ url_for('predict') }}" method="post">
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict'. Did you mean 'static' instead?
[2025-08-16 17:23:05,536: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:23:05] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2025-08-16 17:23:07,449: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/app.py", line 12, in home
    return render_template('index.html')
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/templates/index.html", line 18, in top-level template code
    <form action="{{ url_for('predict') }}" method="post">
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict'. Did you mean 'static' instead?
[2025-08-16 17:23:07,451: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:23:07] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2025-08-16 17:26:53,038: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.36:8080]
[2025-08-16 17:26:53,038: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-16 17:26:55,825: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:26:55] "GET / HTTP/1.1" 200 -]
[2025-08-16 17:27:02,227: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 17:27:02,228: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:27:02,229: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:27:02,230: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:27:02,230: INFO: common: created directory at: artifacts]
[2025-08-16 17:27:02,230: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 17:27:02,230: INFO: data_ingestion: File already exists]
[2025-08-16 17:27:02,231: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 17:27:02,231: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 17:27:02,232: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:27:02,232: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:27:02,233: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:27:02,233: INFO: common: created directory at: artifacts]
[2025-08-16 17:27:02,233: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 17:27:02,235: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 17:27:02,235: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 17:27:02,236: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:27:02,237: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:27:02,237: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:27:02,237: INFO: common: created directory at: artifacts]
[2025-08-16 17:27:02,237: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 17:27:02,244: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 17:27:02,244: INFO: data_transformation: (1199, 12)]
[2025-08-16 17:27:02,244: INFO: data_transformation: (400, 12)]
[2025-08-16 17:27:02,244: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 17:27:02,244: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 17:27:02,245: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:27:02,246: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:27:02,246: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:27:02,246: INFO: common: created directory at: artifacts]
[2025-08-16 17:27:02,246: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 17:27:02,250: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 17:27:02,250: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 17:27:02,251: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:27:02,251: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:27:02,251: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:27:02,251: INFO: common: created directory at: artifacts]
[2025-08-16 17:27:02,252: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 17:27:02,498: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 17:27:02,504: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 17:27:02,613: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:27:02] "GET /train HTTP/1.1" 200 -]
[2025-08-16 17:27:24,905: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:27:24] "GET / HTTP/1.1" 200 -]
[2025-08-16 17:27:25,617: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 17:27:25,618: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:27:25,619: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:27:25,619: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:27:25,619: INFO: common: created directory at: artifacts]
[2025-08-16 17:27:25,619: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 17:27:25,619: INFO: data_ingestion: File already exists]
[2025-08-16 17:27:25,621: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 17:27:25,621: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 17:27:25,622: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:27:25,622: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:27:25,622: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:27:25,622: INFO: common: created directory at: artifacts]
[2025-08-16 17:27:25,622: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 17:27:25,625: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 17:27:25,625: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 17:27:25,626: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:27:25,627: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:27:25,627: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:27:25,627: INFO: common: created directory at: artifacts]
[2025-08-16 17:27:25,628: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 17:27:25,635: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 17:27:25,635: INFO: data_transformation: (1199, 12)]
[2025-08-16 17:27:25,635: INFO: data_transformation: (400, 12)]
[2025-08-16 17:27:25,635: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 17:27:25,635: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 17:27:25,636: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:27:25,636: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:27:25,636: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:27:25,637: INFO: common: created directory at: artifacts]
[2025-08-16 17:27:25,637: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 17:27:25,640: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 17:27:25,640: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 17:27:25,641: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:27:25,641: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:27:25,642: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:27:25,642: INFO: common: created directory at: artifacts]
[2025-08-16 17:27:25,642: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 17:27:25,874: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 17:27:25,880: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 17:27:25,998: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:27:25] "GET /train HTTP/1.1" 200 -]
[2025-08-16 17:29:49,095: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 17:29:49,096: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:29:49,096: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:29:49,097: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:29:49,097: INFO: common: created directory at: artifacts]
[2025-08-16 17:29:49,097: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 17:29:49,097: INFO: data_ingestion: File already exists]
[2025-08-16 17:29:49,098: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 17:29:49,098: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 17:29:49,099: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:29:49,099: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:29:49,099: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:29:49,100: INFO: common: created directory at: artifacts]
[2025-08-16 17:29:49,100: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 17:29:49,102: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 17:29:49,102: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 17:29:49,103: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:29:49,103: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:29:49,104: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:29:49,104: INFO: common: created directory at: artifacts]
[2025-08-16 17:29:49,104: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 17:29:49,110: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 17:29:49,110: INFO: data_transformation: (1199, 12)]
[2025-08-16 17:29:49,110: INFO: data_transformation: (400, 12)]
[2025-08-16 17:29:49,110: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 17:29:49,110: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 17:29:49,111: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:29:49,111: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:29:49,112: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:29:49,112: INFO: common: created directory at: artifacts]
[2025-08-16 17:29:49,112: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 17:29:49,115: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 17:29:49,115: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 17:29:49,116: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:29:49,116: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:29:49,117: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:29:49,117: INFO: common: created directory at: artifacts]
[2025-08-16 17:29:49,117: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 17:29:49,287: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 17:29:49,293: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 17:29:49,400: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:29:49] "GET /train HTTP/1.1" 200 -]
[2025-08-16 17:30:00,450: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:30:00] "GET / HTTP/1.1" 200 -]
[2025-08-16 17:33:47,421: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.36:8080]
[2025-08-16 17:33:47,421: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-16 17:33:49,967: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:33:49] "GET / HTTP/1.1" 200 -]
[2025-08-16 17:33:53,327: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 17:33:53,328: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:33:53,328: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:33:53,329: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:33:53,329: INFO: common: created directory at: artifacts]
[2025-08-16 17:33:53,329: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 17:33:53,329: INFO: data_ingestion: File already exists]
[2025-08-16 17:33:53,330: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 17:33:53,330: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 17:33:53,331: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:33:53,331: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:33:53,332: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:33:53,332: INFO: common: created directory at: artifacts]
[2025-08-16 17:33:53,332: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 17:33:53,334: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 17:33:53,334: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 17:33:53,335: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:33:53,336: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:33:53,336: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:33:53,336: INFO: common: created directory at: artifacts]
[2025-08-16 17:33:53,336: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 17:33:53,342: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 17:33:53,343: INFO: data_transformation: (1199, 12)]
[2025-08-16 17:33:53,343: INFO: data_transformation: (400, 12)]
[2025-08-16 17:33:53,343: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 17:33:53,343: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 17:33:53,344: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:33:53,344: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:33:53,344: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:33:53,344: INFO: common: created directory at: artifacts]
[2025-08-16 17:33:53,344: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 17:33:53,347: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 17:33:53,347: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 17:33:53,348: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:33:53,349: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:33:53,349: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:33:53,349: INFO: common: created directory at: artifacts]
[2025-08-16 17:33:53,349: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 17:33:53,579: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 17:33:53,585: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 17:33:53,692: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:33:53] "[32mGET /train HTTP/1.1[0m" 302 -]
[2025-08-16 17:33:53,702: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:33:53] "GET /?message=Training+Successful... HTTP/1.1" 200 -]
[2025-08-16 17:39:19,506: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.36:8080]
[2025-08-16 17:39:19,506: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-16 17:39:21,751: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:39:21] "GET / HTTP/1.1" 200 -]
[2025-08-16 17:39:24,588: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 17:39:24,590: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:39:24,590: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:39:24,591: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:39:24,591: INFO: common: created directory at: artifacts]
[2025-08-16 17:39:24,591: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 17:39:25,005: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Date: Sat, 16 Aug 2025 16:39:24 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, X-Requested-With,Accept-Encoding, Accept, X-Requested-With
x-repository-download: git clone https://github.com/Vatsal-Founder/MLOPS_project.git
x-raw-download: https://raw.githubusercontent.com/Vatsal-Founder/MLOPS_project/main/datasets/winequality.zip
ETag: W/"e9aedf759e52e8da23b6627e623aa179"
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com *.rel.tunnels.api.visualstudio.com wss://*.rel.tunnels.api.visualstudio.com objects-origin.githubusercontent.com copilot-proxy.githubusercontent.com proxy.individual.githubcopilot.com proxy.business.githubcopilot.com proxy.enterprise.githubcopilot.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com wss://alive-staging.github.com api.githubcopilot.com api.individual.githubcopilot.com api.business.githubcopilot.com api.enterprise.githubcopilot.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com private-avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com release-assets.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com copilotprodattachments.blob.core.windows.net/github-production-copilot-attachments/ github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/
Server: github.com
Accept-Ranges: bytes
Set-Cookie: _gh_sess=GjJH%2B5Xuve9ODjIzf17ptpZ3t7oaR6vESnEagI6%2BQ9TIoipWvcm2pBHJrZtLEcfyypcvmRbSsF4d9XHpZAdKwZvziVyWxdMfWx0lmlq59HW4Img7WB0PjTYdm%2FJCVVWMsq%2BJn1LimDMNciyxIdCuoPuIVgQXMvDqO3XrPHka9Z7byjFureM5oTDTSj55x6ucn%2FHA6pWg8MDp21Ob%2F5kAQfNiW98uuu7SbkItc3VTi5aIP8AUlFvqCgMDDePOegVPitrdJPM5SDaGYYhiAUF40A%3D%3D--ow8P3AMcVPBa09fN--yGixiiygLo%2BTGXoAxy8M%2BA%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.12859706.1755362364; Path=/; Domain=github.com; Expires=Sun, 16 Aug 2026 16:39:24 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Sun, 16 Aug 2026 16:39:24 GMT; HttpOnly; Secure; SameSite=Lax
X-GitHub-Request-Id: D60C:3FC6DA:79592B:9F978A:68A0B43C
connection: close
Transfer-Encoding: chunked

]
[2025-08-16 17:39:25,007: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/main.py", line 12, in <module>
    data_ingestion.initiate_data_ingestion()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/src/MLOPS/pipeline/data_ingestion_pipeline.py", line 17, in initiate_data_ingestion
    data_ingestion.extract_zip_file()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/src/MLOPS/components/data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-08-16 17:39:25,130: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:39:25] "[32mGET /train HTTP/1.1[0m" 302 -]
[2025-08-16 17:39:25,141: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:39:25] "GET /?message=Training+Successful... HTTP/1.1" 200 -]
[2025-08-16 17:40:03,144: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:40:03] "POST /predict HTTP/1.1" 200 -]
[2025-08-16 17:40:36,604: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.36:8080]
[2025-08-16 17:40:36,604: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-16 17:40:39,515: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:40:39] "GET / HTTP/1.1" 200 -]
[2025-08-16 17:40:42,125: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 17:40:42,126: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:40:42,126: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:40:42,127: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:40:42,127: INFO: common: created directory at: artifacts]
[2025-08-16 17:40:42,127: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 17:40:42,127: INFO: data_ingestion: File already exists]
[2025-08-16 17:40:42,128: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/main.py", line 12, in <module>
    data_ingestion.initiate_data_ingestion()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/src/MLOPS/pipeline/data_ingestion_pipeline.py", line 17, in initiate_data_ingestion
    data_ingestion.extract_zip_file()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/src/MLOPS/components/data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-08-16 17:40:42,211: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:40:42] "[32mGET /train HTTP/1.1[0m" 302 -]
[2025-08-16 17:40:42,220: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:40:42] "GET /?message=Training+Successful... HTTP/1.1" 200 -]
[2025-08-16 17:42:07,442: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.36:8080]
[2025-08-16 17:42:07,442: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-16 17:42:09,810: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:42:09] "GET / HTTP/1.1" 200 -]
[2025-08-16 17:42:12,049: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 17:42:12,051: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:42:12,051: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:42:12,052: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:42:12,052: INFO: common: created directory at: artifacts]
[2025-08-16 17:42:12,052: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 17:42:12,052: INFO: data_ingestion: File already exists]
[2025-08-16 17:42:12,052: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/main.py", line 12, in <module>
    data_ingestion.initiate_data_ingestion()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/src/MLOPS/pipeline/data_ingestion_pipeline.py", line 17, in initiate_data_ingestion
    data_ingestion.extract_zip_file()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/src/MLOPS/components/data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/Users/vatsal/Machine Learning/MLOPS/End_to_end_project/MLOPS_project/venv/lib/python3.10/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-08-16 17:42:12,135: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:42:12] "[32mGET /train HTTP/1.1[0m" 302 -]
[2025-08-16 17:42:12,145: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:42:12] "GET /?message=Training+Successful... HTTP/1.1" 200 -]
[2025-08-16 17:43:02,020: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 17:43:02,021: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:43:02,022: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:43:02,022: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:43:02,022: INFO: common: created directory at: artifacts]
[2025-08-16 17:43:02,023: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 17:43:02,466: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D747:31D60:1D446:1C1FB9:68A0B514
Accept-Ranges: bytes
Date: Sat, 16 Aug 2025 16:43:02 GMT
Via: 1.1 varnish
X-Served-By: cache-dub4377-DUB
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1755362582.358412,VS0,VE109
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: f0ad35e242aa918761c35443f58cc42aa4eb597e
Expires: Sat, 16 Aug 2025 16:48:02 GMT
Source-Age: 0

]
[2025-08-16 17:43:02,470: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 17:43:02,470: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 17:43:02,473: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:43:02,473: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:43:02,475: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:43:02,475: INFO: common: created directory at: artifacts]
[2025-08-16 17:43:02,475: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 17:43:02,480: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 17:43:02,480: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 17:43:02,482: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:43:02,483: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:43:02,484: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:43:02,484: INFO: common: created directory at: artifacts]
[2025-08-16 17:43:02,484: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 17:43:02,496: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 17:43:02,496: INFO: data_transformation: (1199, 12)]
[2025-08-16 17:43:02,496: INFO: data_transformation: (400, 12)]
[2025-08-16 17:43:02,496: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 17:43:02,496: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 17:43:02,498: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:43:02,498: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:43:02,499: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:43:02,499: INFO: common: created directory at: artifacts]
[2025-08-16 17:43:02,499: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 17:43:02,504: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 17:43:02,504: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 17:43:02,506: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:43:02,506: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:43:02,507: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:43:02,507: INFO: common: created directory at: artifacts]
[2025-08-16 17:43:02,507: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 17:43:02,765: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 17:43:02,770: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 17:43:23,114: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.36:8080]
[2025-08-16 17:43:23,115: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-16 17:43:26,038: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:43:26] "GET / HTTP/1.1" 200 -]
[2025-08-16 17:43:28,713: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-16 17:43:28,715: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:43:28,715: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:43:28,716: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:43:28,716: INFO: common: created directory at: artifacts]
[2025-08-16 17:43:28,716: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-16 17:43:28,813: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D747:31D60:1D446:1C1FB9:68A0B514
Accept-Ranges: bytes
Date: Sat, 16 Aug 2025 16:43:28 GMT
Via: 1.1 varnish
X-Served-By: cache-dub4363-DUB
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1755362609.826656,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 9dbfedb87e4b314b6a832c6784aef791e24cd787
Expires: Sat, 16 Aug 2025 16:48:28 GMT
Source-Age: 26

]
[2025-08-16 17:43:28,814: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-16 17:43:28,814: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-08-16 17:43:28,815: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:43:28,816: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:43:28,817: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:43:28,817: INFO: common: created directory at: artifacts]
[2025-08-16 17:43:28,817: INFO: common: created directory at: artifacts/data_validation]
[2025-08-16 17:43:28,820: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-08-16 17:43:28,820: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-08-16 17:43:28,821: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:43:28,822: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:43:28,823: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:43:28,823: INFO: common: created directory at: artifacts]
[2025-08-16 17:43:28,823: INFO: common: created directory at: artifacts/data_transformation]
[2025-08-16 17:43:28,831: INFO: data_transformation: Splited data into training and test sets]
[2025-08-16 17:43:28,831: INFO: data_transformation: (1199, 12)]
[2025-08-16 17:43:28,831: INFO: data_transformation: (400, 12)]
[2025-08-16 17:43:28,831: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-08-16 17:43:28,831: INFO: main: >>>>>> stage Model Training stage started <<<<<<]
[2025-08-16 17:43:28,832: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:43:28,833: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:43:28,833: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:43:28,833: INFO: common: created directory at: artifacts]
[2025-08-16 17:43:28,833: INFO: common: created directory at: artifacts/model_trainer]
[2025-08-16 17:43:28,837: INFO: main: >>>>>> stage Model Training stage completed <<<<<<

x==========x]
[2025-08-16 17:43:28,837: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2025-08-16 17:43:28,838: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-08-16 17:43:28,838: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-16 17:43:28,839: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-16 17:43:28,839: INFO: common: created directory at: artifacts]
[2025-08-16 17:43:28,839: INFO: common: created directory at: artifacts/model_evaluation]
[2025-08-16 17:43:29,070: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-08-16 17:43:29,076: INFO: main: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x]
[2025-08-16 17:43:29,186: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:43:29] "[32mGET /train HTTP/1.1[0m" 302 -]
[2025-08-16 17:43:29,195: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:43:29] "GET /?message=Training+Successful... HTTP/1.1" 200 -]
[2025-08-16 17:43:57,321: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:43:57] "POST /predict HTTP/1.1" 200 -]
[2025-08-16 17:45:53,031: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.36:8080]
[2025-08-16 17:45:53,031: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-16 17:45:55,250: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:45:55] "GET / HTTP/1.1" 200 -]
[2025-08-16 17:46:22,871: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:46:22] "POST /predict HTTP/1.1" 200 -]
[2025-08-16 17:47:06,065: INFO: _internal: 127.0.0.1 - - [16/Aug/2025 17:47:06] "POST /predict HTTP/1.1" 200 -]
